version: '3'
services:
  web:
    image: nginx
    labels:
      - "traefik.frontend.rule=Host:web.localhost"
  blog:
    image: dockercloud/hello-world
    labels:
      - "traefik.frontend.rule=Host:blog.localhost"
  whoami:
    image: containous/whoami
    labels:
      - "traefik.frontend.rule=Host:whoami.localhost"
  lb:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
